# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='stations',
            field=models.ManyToManyField(related_name='stations', through='train.Status', to='train.Station'),
        ),
        migrations.AlterField(
            model_name='train',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
