# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.CharField(max_length=500)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.Station')),
            ],
        ),
    ]
