# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=10)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.Station')),
            ],
        ),
    ]
