# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_auto_20170330_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='number',
            new_name='code',
        ),
        migrations.AddField(
            model_name='station',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
