# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_train_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='id',
        ),
        migrations.AlterField(
            model_name='train',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
